[package]
name = "snippeteer"
version = "0.1.0"
authors = ["Benedikt Schatz <schlchtwtrfrnt@gmail.com>"]

[dependencies]
chrono = "0.3"
gdk = "0.11.0"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]
